Fig = figure('Name', 'Diode-Resistor Circuit', ...
    'Units', 'normalized', ...
    'Position', [0.2, 0.2, 0.6, 0.6]);

backgroundImage = 'download.jpg';  
ax = axes('Parent', Fig, 'Position', [0 0 1 1]); 
imshow(backgroundImage, 'Parent', ax);
set(ax, 'Visible', 'off');


uicontrol('Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.3 0.85 0.4 0.1], ... 
    'String', 'Diode-Resistor Circuit', ...
    'FontSize', 18, ... 
    'FontWeight', 'bold', ...
    'ForegroundColor', [1 0.75 0.8], ... 
    'BackgroundColor', [0.1 0.1 0.3]); 

uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.2 0.7 0.6 0.1], ...
    'String', 'Documentation', ...
    'FontSize', 12, ...
    'BackgroundColor', [0.1 0.1 0.3], ... 
    'ForegroundColor', [1 0.75 0.8], ...
    'Callback', 'documentation();');

uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.2 0.55 0.6 0.1], ...
    'String', 'Characteristics', ...
    'FontSize', 12, ...
    'BackgroundColor', [0.1 0.1 0.3], ... 
    'ForegroundColor', [1 0.75 0.8], ... 
    'Callback', 'showCharacteristics();');

uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'FontWeight', 'bold', ...
    'Fontsize', 12, ...
    'BackgroundColor', [1 0.75 0.8], ...
    'Position', [0.80 0.03 0.1 0.06], ...
    'String', 'Close', ...
    'Callback', 'close();');

