function showCharacteristics(~, ~)
   
    function [t, vout, vin] = dr(idx, A, f, n, VBias)
        if nargin == 4
            VBias = 0; 
        end

        T = 1 / f;
        stepsize = T / 100;
        t = 0:stepsize:n*T;
        vin = A * sin(2 * pi * f * t); 

        switch idx
            case 2
                vout = vin;
                vout(vin < VBias) = VBias; 
            case 3
                vout = vin - 0.7; 
                vout(vin < VBias + 0.7) = VBias;
            otherwise
                disp('Unknown option');
                vout = zeros(size(vin));
        end
    end

    A = 5; f = 50; n = 3; idx = 1;
    [t, vout, vin] = dr(idx, A, f, n);

    Fig2 = figure('Name', "DR Circuit", ...
        'Units', 'normalized', ...
        'Position', [.3 .3 .6 .6], ...
        'NumberTitle', 'off', ...
        'Color', [0.94, 0.9, 0.96]);

   uicontrol('Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.15 0.90 0.5 0.08], ...
    'String', 'DR Circuit', ...
    'FontSize', 30, ...
    'FontWeight', 'bold', ...
    'FontName', 'Georgia', ... 
    'ForegroundColor', [0.5, 0, 0.5], ... 
    'BackgroundColor', [0.94, 0.9, 0.96]);

    imagePath = 'DR_circuit.jpg'; 
    img = imread(imagePath);

    ax = axes('Parent', Fig2, ...
    'Position', [0.28, 0.35, 0.28, 0.39]); 
    imshow(img, 'Parent', ax);
    set(ax, 'XTick', [], 'YTick', []); 
    
sineWavePanel = uipanel('Parent', Fig2, 'Title', 'Sine Wave', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'Position', [0.08, 0.6, 0.15, 0.3], ...
    'BackgroundColor', [0.9, 0.8, 1], ... 
    'ForegroundColor', [0.5, 0.0, 0.5]);  

uicontrol('Style', 'text', ...
    'Parent', sineWavePanel, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.8 0.3 0.1], ...
    'String', 'A:', ...
    'FontSize', 10, ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.5, 0.0, 0.5], ...
    'BackgroundColor', [0.9, 0.8, 1]); 

editA = uicontrol('Style', 'edit', ...
    'Parent', sineWavePanel, ...
    'Units', 'normalized', ...
    'Position', [0.4 0.8 0.5 0.1], ...
    'BackgroundColor', 'white', ...
    'FontSize', 9, ...
    'String', '5', ...
    'Callback', @(src, event) updatePlot(dropdown));

uicontrol('Style', 'text', ...
    'Parent', sineWavePanel, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.6 0.3 0.1], ...
    'String', 'f:', ...
    'FontSize', 10, ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.5, 0.0, 0.5], ... 
    'BackgroundColor', [0.9, 0.8, 1]); 

editF = uicontrol('Style', 'edit', ...
    'Parent', sineWavePanel, ...
    'Units', 'normalized', ...
    'Position', [0.4 0.6 0.5 0.1], ...
    'BackgroundColor', 'white', ...
    'FontSize', 9, ...
    'String', '50', ...
    'Callback', @(src, event) updatePlot(dropdown));

uicontrol('Style', 'text', ...
    'Parent', sineWavePanel, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.4 0.3 0.1], ...
    'String', 'n:', ...
    'FontSize', 10, ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.5, 0.0, 0.5], ... 
    'BackgroundColor', [0.9, 0.8, 1]); 

editN = uicontrol('Style', 'edit', ...
    'Parent', sineWavePanel, ...
    'Units', 'normalized', ...
    'Position', [0.4 0.4 0.5 0.1], ...
    'BackgroundColor', 'white', ...
    'FontSize', 9, ...
    'String', '3', ...
    'Callback', @(src, event) updatePlot(dropdown));

diodePanel = uipanel('Parent', Fig2, 'Title', 'Diode Model', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'Position', [0.08, 0.3, 0.15, 0.25], ... 
    'BackgroundColor', [0.9, 0.8, 1], ...
    'ForegroundColor', [0.5, 0.0, 0.5]);  

dropdown = uicontrol('Style', 'popupmenu', ...
    'Parent', diodePanel, ...
    'String', {'<none>', 'Ideal', 'Constant voltage drop'}, ...
    'Units', 'normalized', ...
    'Position', [0.2, 0.4, 0.6, 0.1], ...
    'Callback', @(src, event) updatePlot(src));


    returnButton = uicontrol('Style', 'pushbutton', ...
        'Parent', Fig2, ...
        'Units', 'normalized', ...
        'Position', [0.08 0.2 0.15 0.05], ... 
        'String', 'Return', ...
        'FontSize', 12, ...
        'BackgroundColor', [0.1 0.1 0.3], ...
        'ForegroundColor', [1 0.75 0.8], ...
        'Callback', @(src, event) resetParameters());

    uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'FontWeight', 'bold', ...
    'Fontsize', 12, ...
    'BackgroundColor', [1 0.75 0.8], ...
    'Position', [0.1 0.09 0.1 0.06], ...
    'String', 'Close', ...
    'Callback', 'close();');

    ax_vtc = axes('Parent', Fig2, 'Position', [0.62, 0.58, 0.35, 0.3]);
    plot(ax_vtc, vin, vout);
    xlabel(ax_vtc, 'Input Voltage (V)');
    ylabel(ax_vtc, 'Output Voltage (V)');
    title(ax_vtc, 'Voltage Transfer Characteristic (VTC)');


title(ax_vtc, 'Voltage Transfer Characteristic (VTC)', ...
    'Color', [0.4, 0.1, 0.2], ... 
    'FontSize', 12, ...            
    'FontWeight', 'bold');         

plotPanel = uipanel('Parent', Fig2, 'Title', 'Waveforms', ...
    'Position', [0.59, 0.05, 0.4, 0.45], ... 
    'BackgroundColor', [0.9, 0.8, 1], ... 
    'ForegroundColor', [0.4, 0.1, 0.2]); 

ax1 = axes('Parent', plotPanel, 'Position', [0.1, 0.6, 0.8, 0.35]);
plot(ax1, t, vin);
ylabel(ax1, "v_I_N", 'Color', [0.1, 0.3, 0.7]);  
xlabel(ax1, 'Time', 'Color', [0.1, 0.3, 0.7]);  

ax2 = axes('Parent', plotPanel, 'Position', [0.1, 0.15, 0.8, 0.35]);
plot(ax2, t, vout);
ylabel(ax2, "v_O_U_T", 'Color', [0.1, 0.3, 0.7]); 
xlabel(ax2, 'Time', 'Color', [0.1, 0.3, 0.7]);  


function updatePlot(dropdown)
  
    idx = dropdown.Value;
    
    A = str2double(editA.String);
    f = str2double(editF.String);
    n = str2double(editN.String);
    
    [t, vout, vin] = dr(idx, A, f, n);
    
  
    plot(ax1, t, vin);
    plot(ax2, t, vout);
    
    plot(ax_vtc, vin, vout);
    
    title(ax_vtc, 'Voltage Transfer Characteristic (VTC)', ...
        'Color', [0.4, 0.1, 0.2], ...  
        'FontSize', 12, ...           
        'FontWeight', 'bold');         

    xlabel(ax_vtc, 'Input Voltage (V)', 'Color', [0.1, 0.3, 0.7]);  
    ylabel(ax_vtc, 'Output Voltage (V)', 'Color', [0.1, 0.3, 0.7]); 
    
    xlabel(ax1, 'Time', 'Color', [0.1, 0.3, 0.7]); 
    ylabel(ax1, 'v_I_N', 'Color', [0.1, 0.3, 0.7]); 
    
    xlabel(ax2, 'Time', 'Color', [0.1, 0.3, 0.7]);
    ylabel(ax2, 'v_O_U_T', 'Color', [0.1, 0.3, 0.7]); 
end


    function resetParameters()
        
        dropdown.Value = 1;  

        editA.String = '5';  
        editF.String = '50'; 
        editN.String = '3'; 

        updatePlot(dropdown);
    end
end
